steps:
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
    - name: 'gcr.io/cloud-builders/gsutil'
      args:
          [
              '-m',
              'rsync',
              '-r',
              '-c',
              '-d',
              './client/dist',
              'gs://www.anshul.art',
          ]
    - name: 'gcr.io/cloud-builders/gsutil'
      args:
          [
              '-m',
              'setmeta',
              '-h',
              'Content-Encoding:gzip',
              'gs://www.anshul.art/*.js.gz',
          ]
