steps:
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
    - name: 'gcr.io/cloud-builders/gsutil'
      args:
          [
              '-m',
              'cp',
              '-r',
              '-c',
              '-z',
              './client/dist',
              'gs://www.anshul.art',
          ]
